// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: day_of_week.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DayOfWeek_DayOfWeek int32

const (
	DayOfWeek_UNKNOWN   DayOfWeek_DayOfWeek = 0
	DayOfWeek_Monday    DayOfWeek_DayOfWeek = 1
	DayOfWeek_Tuesday   DayOfWeek_DayOfWeek = 2
	DayOfWeek_Wednesday DayOfWeek_DayOfWeek = 3
	DayOfWeek_Thursday  DayOfWeek_DayOfWeek = 4
	DayOfWeek_Friday    DayOfWeek_DayOfWeek = 5
	DayOfWeek_Saturday  DayOfWeek_DayOfWeek = 6
	DayOfWeek_Sunday    DayOfWeek_DayOfWeek = 7
)

// Enum value maps for DayOfWeek_DayOfWeek.
var (
	DayOfWeek_DayOfWeek_name = map[int32]string{
		0: "UNKNOWN",
		1: "Monday",
		2: "Tuesday",
		3: "Wednesday",
		4: "Thursday",
		5: "Friday",
		6: "Saturday",
		7: "Sunday",
	}
	DayOfWeek_DayOfWeek_value = map[string]int32{
		"UNKNOWN":   0,
		"Monday":    1,
		"Tuesday":   2,
		"Wednesday": 3,
		"Thursday":  4,
		"Friday":    5,
		"Saturday":  6,
		"Sunday":    7,
	}
)

func (x DayOfWeek_DayOfWeek) Enum() *DayOfWeek_DayOfWeek {
	p := new(DayOfWeek_DayOfWeek)
	*p = x
	return p
}

func (x DayOfWeek_DayOfWeek) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DayOfWeek_DayOfWeek) Descriptor() protoreflect.EnumDescriptor {
	return file_day_of_week_proto_enumTypes[0].Descriptor()
}

func (DayOfWeek_DayOfWeek) Type() protoreflect.EnumType {
	return &file_day_of_week_proto_enumTypes[0]
}

func (x DayOfWeek_DayOfWeek) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DayOfWeek_DayOfWeek.Descriptor instead.
func (DayOfWeek_DayOfWeek) EnumDescriptor() ([]byte, []int) {
	return file_day_of_week_proto_rawDescGZIP(), []int{0, 0}
}

type DayOfWeek struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DayOfWeek DayOfWeek_DayOfWeek `protobuf:"varint,1,opt,name=day_of_week,json=dayOfWeek,proto3,enum=udemy.DayOfWeek_DayOfWeek" json:"day_of_week,omitempty"`
}

func (x *DayOfWeek) Reset() {
	*x = DayOfWeek{}
	if protoimpl.UnsafeEnabled {
		mi := &file_day_of_week_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DayOfWeek) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayOfWeek) ProtoMessage() {}

func (x *DayOfWeek) ProtoReflect() protoreflect.Message {
	mi := &file_day_of_week_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayOfWeek.ProtoReflect.Descriptor instead.
func (*DayOfWeek) Descriptor() ([]byte, []int) {
	return file_day_of_week_proto_rawDescGZIP(), []int{0}
}

func (x *DayOfWeek) GetDayOfWeek() DayOfWeek_DayOfWeek {
	if x != nil {
		return x.DayOfWeek
	}
	return DayOfWeek_UNKNOWN
}

var File_day_of_week_proto protoreflect.FileDescriptor

var file_day_of_week_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x61, 0x79, 0x5f, 0x6f, 0x66, 0x5f, 0x77, 0x65, 0x65, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75, 0x64, 0x65, 0x6d, 0x79, 0x22, 0xc9, 0x01, 0x0a, 0x09, 0x44,
	0x61, 0x79, 0x4f, 0x66, 0x57, 0x65, 0x65, 0x6b, 0x12, 0x3a, 0x0a, 0x0b, 0x64, 0x61, 0x79, 0x5f,
	0x6f, 0x66, 0x5f, 0x77, 0x65, 0x65, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e,
	0x75, 0x64, 0x65, 0x6d, 0x79, 0x2e, 0x44, 0x61, 0x79, 0x4f, 0x66, 0x57, 0x65, 0x65, 0x6b, 0x2e,
	0x44, 0x61, 0x79, 0x4f, 0x66, 0x57, 0x65, 0x65, 0x6b, 0x52, 0x09, 0x64, 0x61, 0x79, 0x4f, 0x66,
	0x57, 0x65, 0x65, 0x6b, 0x22, 0x74, 0x0a, 0x09, 0x44, 0x61, 0x79, 0x4f, 0x66, 0x57, 0x65, 0x65,
	0x6b, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x4d, 0x6f, 0x6e, 0x64, 0x61, 0x79, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x75,
	0x65, 0x73, 0x64, 0x61, 0x79, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x57, 0x65, 0x64, 0x6e, 0x65,
	0x73, 0x64, 0x61, 0x79, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x68, 0x75, 0x72, 0x73, 0x64,
	0x61, 0x79, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x72, 0x69, 0x64, 0x61, 0x79, 0x10, 0x05,
	0x12, 0x0c, 0x0a, 0x08, 0x53, 0x61, 0x74, 0x75, 0x72, 0x64, 0x61, 0x79, 0x10, 0x06, 0x12, 0x0a,
	0x0a, 0x06, 0x53, 0x75, 0x6e, 0x64, 0x61, 0x79, 0x10, 0x07, 0x4a, 0x04, 0x08, 0x2a, 0x10, 0x2b,
	0x4a, 0x04, 0x08, 0x37, 0x10, 0x43, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_day_of_week_proto_rawDescOnce sync.Once
	file_day_of_week_proto_rawDescData = file_day_of_week_proto_rawDesc
)

func file_day_of_week_proto_rawDescGZIP() []byte {
	file_day_of_week_proto_rawDescOnce.Do(func() {
		file_day_of_week_proto_rawDescData = protoimpl.X.CompressGZIP(file_day_of_week_proto_rawDescData)
	})
	return file_day_of_week_proto_rawDescData
}

var file_day_of_week_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_day_of_week_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_day_of_week_proto_goTypes = []interface{}{
	(DayOfWeek_DayOfWeek)(0), // 0: udemy.DayOfWeek.DayOfWeek
	(*DayOfWeek)(nil),        // 1: udemy.DayOfWeek
}
var file_day_of_week_proto_depIdxs = []int32{
	0, // 0: udemy.DayOfWeek.day_of_week:type_name -> udemy.DayOfWeek.DayOfWeek
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_day_of_week_proto_init() }
func file_day_of_week_proto_init() {
	if File_day_of_week_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_day_of_week_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DayOfWeek); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_day_of_week_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_day_of_week_proto_goTypes,
		DependencyIndexes: file_day_of_week_proto_depIdxs,
		EnumInfos:         file_day_of_week_proto_enumTypes,
		MessageInfos:      file_day_of_week_proto_msgTypes,
	}.Build()
	File_day_of_week_proto = out.File
	file_day_of_week_proto_rawDesc = nil
	file_day_of_week_proto_goTypes = nil
	file_day_of_week_proto_depIdxs = nil
}
